version: "3.7"
services:
    server:
        image: docker.pkg.github.com/qvazi/fibonacci-react-node-express-mysql/fibonacci-react-node-express-mysql:latest
        ports:
            - "8080:8080"
        environment: 
            NODE_ENV: production
            DB_HOST: database
    database:
        image: mysql
        restart: always
        command: --init-file /data/application/init.sql
        volumes:
            - ./server/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: 123123
            MYSQL_DATABASE: testdb
