version: "3.7"
services:
    server:
        build: .
        ports:
            - "8080:8080"
        environment: 
            NODE_ENV: production
            MYSQL_HOST: 'database'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'rootPassword'
            MYSQL_DB: 'fibonacci'
    database:
        image: mysql
        environment:
            MYSQL_ROOT_USER: 'root'
            MYSQL_ROOT_PASSWORD: 'rootPassword'
            MYSQL_DATABASE: 'fibonacci'
